### ISSUE TITLE
The parser crashes when some values appear more than once

### ISSUE THREAD

**Issue by NoXPhasma** [timkurvers/wine-log-explorer#22]
The parser crashes because of a value being provided more than once in the log. Error message:

```js
Error: [@mantine/core] Duplicate options are not supported. Option with value "01bc" was provided more than once
    at Xy@https://timkurvers.github.io/wine-log-explorer/assets/wine-log-explorer-B_CixmYh.js:83:128487
    at Xy@https://timkurvers.github.io/wine-log-explorer/assets/wine-log-explorer-B_CixmYh.js:83:128198
    at n_@https://timkurvers.github.io/wine-log-explorer/assets/wine-log-explorer-B_CixmYh.js:83:129662
    at qu@https://timkurvers.github.io/wine-log-explorer/assets/wine-log-explorer-B_CixmYh.js:30:16998
    at hv@https://timkurvers.github.io/wine-log-explorer/assets/wine-log-explorer-B_CixmYh.js:32:43963
    at fv@https://timkurvers.github.io/wine-log-explorer/assets/wine-log-explorer-B_CixmYh.js:32:39729
    at Vw@https://timkurvers.github.io/wine-log-explorer/assets/wine-log-explorer-B_CixmYh.js:32:39657
    at sl@https://timkurvers.github.io/wine-log-explorer/assets/wine-log-explorer-B_CixmYh.js:32:39508
    at Gc@https://timkurvers.github.io/wine-log-explorer/assets/wine-log-explorer-B_CixmYh.js:32:35875
    at cv@https://timkurvers.github.io/wine-log-explorer/assets/wine-log-explorer-B_CixmYh.js:32:34826
    at S@https://timkurvers.github.io/wine-log-explorer/assets/wine-log-explorer-B_CixmYh.js:17:1554
    at B@https://timkurvers.github.io/wine-log-explorer/assets/wine-log-explorer-B_CixmYh.js:17:1915
    at 
```

This can be reproduced with this log file: [steam-489830.log](https://github.com/user-attachments/files/17120068/steam-489830.log)

**Comment by timkurvers** [comment]
Thanks for the reproduction case 🙏

Think the assumption that thread IDs would be unique does not hold, or there's something odd with this log in particular. Either way, definitely a bug 💯

**Comment by timkurvers** [comment]
This should be live now in v0.5.5, took a while to deploy due to a GitHub Actions outage. Thanks again!

**Comment by NoXPhasma** [comment]
Can confirm, works.
